### ISSUE TITLE
Mono support?

### ISSUE THREAD

**Issue by kurtsansom** [Mizux/cmake-swig#10]
Would it be possible to support mono and is that of interest for this example?

**Comment by Mizux** [comment]
I won't since Microsoft release the .Net Core SDK for Linux, macOS and Windows it is not needed anymore to rely on the mono toolchain IMHO.

FYI:
1. While targeting `netstandard2.0` for library (and `netcorapp2.1` for sample) through the use of .Net Core SDK >= 3.1 LTS and the dotnet cli (IIRC) SWIG should generate code nearly compatible with net4.5.2 TFM
2. On my todo list test the .Net5 SDK
3. Did you take a look at https://github.com/Mizux/dotnet-native/blob/main/README.md ? (basically cmake-swig BUT for .Net only)

**Comment by kurtsansom** [comment]
I was primarily interested in the cmake+swig+csharp and didn't see the dotnet-native project  yet.
